### ISSUE TITLE
Stuck before training

### ISSUE THREAD

**Issue by minsu1206** [huanngzh/EpiDiff#5]
Hi.
Thanks for sharing nice work.

I tried to train the model with original dataset (using your example set) or with my custom dataset.

But I got stuck when the number of gpus is larger than 1 (DDP setting)

![image](https://github.com/huanngzh/EpiDiff/assets/59243570/9afb3e77-8504-43bc-8325-e611bcbd70e2)

I found that training with single GPU has no problem. But only multi GPU makes this problem.

How to solve this problem?

Thanks in advance.

**Comment by huanngzh** [comment]
Hi, I haven't encountered a similar problem. Do you have more detailed output or instructions?

**Comment by minsu1206** [comment]
Hi. I forgot to close this issue.

I solved this issue ; No code error
https://github.com/huggingface/accelerate/issues/2174
This repo is the key to solve.

I'll close the issue. Thank you for your answer.
